[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dario Zubaray", email = "dzubaray@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.1",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
fastapi-blog = "fastapi_blog:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
